ams::student
String ams.student.fName
String ams.student.lName
int ams.student.id
Date ams.student.dob
String ams.student.contact_phone
String ams.student.card_id
dbControl ams.student.boop
ams.student.student()
References ams.dbControl.dbComd, ams.student.SQLStudent, ams.student.print, ams.dbControl.doClose.
String ams.student.SQLStudent(String column, String table)
DeprecatedThe idea here is to have a ready SQL statement that can be multi-purposed column This is a string. To include more than one column, make sure to pass all the needed columns as a string. ie: "col1, col2" table This is a string. At a later time, this will be able to include multiple tables Returns an SQL command
Referenced by ams.student.student.
static void ams.student.cardIDLookUp(String cardid)
This method will compare the card_id (from the database) with the UID of the card that is scanned cardid This will be called forth from the database. //TO-DO Figure out how to pass SQL parameters through java.
References ams.dbControl.dbComd, ams.student.print, ams.dbControl.doClose.
Referenced by ams.CardConnection.run.
static void ams.student.print()
Referenced by ams.student.student, ams.student.cardIDLookUp.
static void ams.student.getProfile()
Used when a student wishes to see their profile and attendance records This will be automatically called if AMS is inactive (amsActivate class will determine this)