ams::UserInterface
final ImageIcon ams.UserInterface.ICON_ACTIVE
final ImageIcon ams.UserInterface.ICON_INACTIVE
String ams.UserInterface.uid_placeholder
Referenced by ams.ClassManager.classListFiller2, ams.ClassManager.class2ListFiller2.
String ams.UserInterface.UID
boolean ams.UserInterface.x
javax.swing.JLabel ams.UserInterface.ACTIVE_ICON
Referenced by ams.updateChecker.updateActiveCheck.
javax.swing.JLabel ams.UserInterface.INACTIVE_ICON
Referenced by ams.updateChecker.updateActiveCheck.
javax.swing.JButton ams.UserInterface.viewStudentsButton
Referenced by ams.CardConnection.run.
java.awt.Label ams.UserInterface.StudentCall
javax.swing.JButton ams.UserInterface.backToStart
java.awt.Label ams.UserInterface.currentClass
javax.swing.JButton ams.UserInterface.jButton1
javax.swing.JLabel ams.UserInterface.jLabel1
javax.swing.JLayeredPane ams.UserInterface.jLayeredPane1
javax.swing.JPanel ams.UserInterface.jPanel1
javax.swing.JPanel ams.UserInterface.jPanel2
javax.swing.JPanel ams.UserInterface.jPanel3
javax.swing.JPanel ams.UserInterface.jPanel4
javax.swing.JScrollPane ams.UserInterface.jScrollPane1
javax.swing.JLabel ams.UserInterface.mainBG_start
javax.swing.JPanel ams.UserInterface.main_start
javax.swing.JTable ams.UserInterface.studentListOnStart
java.awt.Label ams.UserInterface.classCall
ams.UserInterface.UserInterface()
Creates new form UserInterface
void ams.UserInterface.initComponents()
This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
void ams.UserInterface.viewStudentsButtonActionPerformed(java.awt.event.ActionEvent evt)
void ams.UserInterface.jButton1MouseReleased(java.awt.event.MouseEvent evt)
void ams.UserInterface.backToStartMouseReleased(java.awt.event.MouseEvent evt)
void ams.UserInterface.jButton1ActionPerformed(java.awt.event.ActionEvent evt)
static ImageIcon ams.UserInterface.createImageIcon(String path, String description)
Returns an ImageIcon, or null if the path was invalid. This is to allow images to brought in without a NullPointerException Resourced from : https://stackoverflow.com/questions/13151979/null-pointer-exception-when-an-imageicon-is-added-to-jbutton-in-netbeans
static ImageIcon ams.UserInterface.getIcon(String x)
Need a way to access non-static methods from static context Referenced from https://www.javacodegeeks.com/2017/10/can-non-static-method-access-static-variablemethod-java.html x Picture URL/File Path location ImageIcon The image file will now be able to be used in java.
static void ams.UserInterface.updateStudent(String UID)
This is to update the name bar of the student/employee. I just stuck to student coz it's easier UID Card UID.
References ams.InterfaceCmds.getCurrentUID, ams.InterfaceCmds.getCurrentSwipe.
Referenced by ams.CardConnection.run.
static void ams.UserInterface.updateActiveCheck(boolean success)
References ams.updateChecker.updateActiveCheck.
Referenced by ams.amsActivate.ActivateOrNah, ams.CardConnection.run.