ams::Presence
dbControl ams.Presence.db
dbControl ams.Presence.dbUpdate
dbLookUp ams.Presence.LookUp
ClassThread ams.Presence.classC
boolean ams.Presence.instructorIN
boolean ams.Presence.readStudentUID
String ams.Presence.UIStudentName
Referenced by ams.InterfaceCmds.getCurrentUID.
ams.Presence.Presence()
static boolean ams.Presence.timeCheck()
The timeCheck() method is meant to be an inclusive method that can be used anyhwhere in the application to check whether the current time has any ongoing classes. Time Check Positive or Negative
References ams.ClassThread.classCheck, ams.dbControl.dbComd, ams.Presence.toMins, ams.dbControl.doClose.
Referenced by ams.Presence.MarkPresent, ams.Presence.UpPresence, ams.Presence.DownPresence, ams.Presence.InstructorPresence.
static void ams.Presence.FifteenMinActivate()
There are times when the instructor is late or not present during a lecture. This method is geared towards activating the the AMS 15 minutes into class automatically so students who've attended may mark their presence in the system.
References ams.dbControl.dbComd, ams.Presence.toMins, ams.dbControl.doClose, ams.CardConnection.counter.
Referenced by ams.CardConnection.run.
static int ams.Presence.toMins(String s)
This method is meant for the timeCheck method. It returns the minute format for DD:HH:MM s This is a method used to turn HH:MM:SS format into one int number in MINUTES only. It helps with time comparisons. HoursInMins
Referenced by ams.ams_main.main, ams.Presence.timeCheck, ams.Presence.FifteenMinActivate.
static void ams.Presence.MarkPresent(String UID)
References ams.ClassThread.classCheck, ams.Presence.timeCheck, ams.dbControl.doConnect, ams.dbControl.doClose.
Referenced by ams.ams_main.main, ams.amsActivate.activateAms.
static void ams.Presence.AdjustPresence(String UID, boolean req)
The following three methods are geared towards adjusting a student's presence in a certain class. UID Card UID req req
References ams.Presence.UpPresence, ams.Presence.DownPresence.
static void ams.Presence.UpPresence(String UID)
References ams.ClassThread.classCheck, ams.Presence.timeCheck, ams.dbControl.doConnect, ams.dbControl.doClose.
Referenced by ams.Presence.AdjustPresence.
static void ams.Presence.DownPresence(String UID)
In case the instructor needs to lower someone's presence count for a class This can only be used effectively within the time range of a particular class session UID
References ams.ClassThread.classCheck, ams.Presence.timeCheck, ams.dbControl.doConnect, ams.dbControl.doClose.
Referenced by ams.Presence.AdjustPresence.
static void ams.Presence.InstructorPresence(String UID)
InstructorPresence will have multiple functions: • It'll mark their presence for that class • If this method is not met, the 15 minute activation of the AMS will automatically commence UID
References ams.ClassThread.classCheck, ams.Presence.timeCheck, ams.dbControl.doConnect, ams.dbControl.doClose.
Referenced by ams.CardConnection.run.
static void ams.Presence.getPresncePercentage(String UID)