ams::CardConnection
CardTerminal ams.CardConnection.terminal
boolean ams.CardConnection.running
boolean ams.CardConnection.sendConfirmation
final CommandAPDU ams.CardConnection.GET_UID_COMMAND_APDU
final int ams.CardConnection.ESCAPE_COMMAND
String ams.CardConnection.cardUID
Referenced by ams.ams_main.main, ams.InterfaceCmds.getCurrentUID.
int ams.CardConnection.counter
Referenced by ams.amsActivate.ActivateOrNah, ams.amsActivate.activateAms, ams.CardConnection.run, ams.Presence.FifteenMinActivate.
int ams.CardConnection.view_counter
ams.CardConnection.CardConnection()
boolean ams.CardConnection.enablePlugnPlay()
Enables the USB NFC reader to be removed and then reinserted without errors. Based entirely on: http://stackoverflow.com/a/16987873 boolean of whether it's a success or not.
Referenced by ams.ams_main.main.
boolean ams.CardConnection.initateTerminal()
Initiates the card terminal connection, i.e. connects to the USB NFC Reader. boolean of whether it's a success or not.
Referenced by ams.ams_main.main.
void ams.CardConnection.disableSound(boolean set)
This method disables the buzzer sound of the USB NCF Reader based on a boolean A neat option I found while researching the card reader ( API-ACR122U-2.02.pdf Page 28 - 6.7- Set Buzzer output) Some issues with this method is that I couldn't figure out how to enable it to work with the method enablePlugnPlay() as it wasn't a priority. set boolean on whether it's set as disabled or not
Referenced by ams.ams_main.main.
void ams.CardConnection.run()
This method is the main loop for the CardConnection, it'll continously check for new cards. This will be used as something like: text : new Thread(CardConnection).start();
References ams.CardConnection.counter, ams.Presence.FifteenMinActivate, ams.ClassThread.classCheck, ams.UserInterface.updateActiveCheck, ams.CardConnection.cardUID, ams.UserInterface.updateStudent, ams.student.cardIDLookUp, ams.dbLookUp.uidCheck, ams.UserInterface.viewStudentsButton, ams.dbControl.dbComd, ams.Presence.InstructorPresence, ams.amsActivate.ActivateOrNah, ams.dbControl.doClose.
void ams.CardConnection.pause()
Will pause the CardConnection. I don't think I ever needed to use it But to have an unused method is better than having to make one later on I think. InterruptedException InterruptException
void ams.CardConnection.resume()
Will resume the CardConnection. InterruptedException InterruptedException
static String ams.CardConnection.cardUID()
For instances where we call the card UID from another class Returns the card's UID in String format.
Referenced by ams.CardConnection.run.