ams::ClassThread
int [][] ams.ClassThread.class_table
ams.ClassThread.ClassThread()
static int [][] ams.ClassThread.ActiveClassesList()
Creates an array of the active classes of a current semester every time it's called. a 2D array, index [x][0] is for the class_id, [x][1] is for the time of that class_start in minutes.
References ams.dbControl.dbComd, ams.dbControl.doClose, ams.ClassThread.toMins.
Referenced by ams.ams_main.main.
static int ams.ClassThread.toMins(String s)
For some reason, accessing another method within the DB call loop (in the ActiveClassesList() method) renders the whole operation as void. I added another copy of the toMins() method originally from Presence.java to help counter this error. s
Referenced by ams.ClassThread.ActiveClassesList, ams.ClassThread.classCheck.
static int ams.ClassThread.classCheck()
This method is to check which "time slot" of the day as class is ongoing. The classCheck() method is written with knowledge of the tables in the database. The number returned will be used in SQL queries where we need to obtain the class list of active classes
References ams.ClassThread.toMins.
Referenced by ams.CardConnection.run, ams.InterfaceCmds.getCurrentClass, ams.Presence.timeCheck, ams.Presence.MarkPresent, ams.Presence.UpPresence, ams.Presence.DownPresence, ams.Presence.InstructorPresence.