ams::dbControl
Connection ams.dbControl.con
Statement ams.dbControl.COMMANDTHEE
Statement ams.dbControl.DO_THE_THING
ResultSet ams.dbControl.rs
ResultSet ams.dbControl.rsUpdate
ResultSet ams.dbControl.rsUpdateMe
String ams.dbControl.SQL
ams.dbControl.dbControl()
static void ams.dbControl.dbComd(String sqlcmd)
This method is aimed at making a general use method for SQL statements. When using this method, be sure to add the "doClose();" method in your finally block in the end of the try-catch. sqlcmd The all-in-one SQL query (READ ONLY) method. The WRITABLE method is doComdUpdate(String)
References ams.dbControl.doConnect.
Referenced by ams.CardConnection.run, ams.ClassManager.classListFiller2, ams.ClassManager.timeListFiller2, ams.ClassManager.class2ListFiller2, ams.ClassManager.timingsListFiller2, ams.ClassThread.ActiveClassesList, ams.dbControl.getID, ams.dbLookUp.uidCheck, ams.InterfaceCmds.getCurrentClass, ams.InterfaceCmds.getCurrentUID, ams.InterfaceCmds.getCurrentSwipe, ams.Presence.timeCheck, ams.Presence.FifteenMinActivate, ams.student.student, ams.student.cardIDLookUp.
static void ams.dbControl.dbComdUpdate(String sqlcmd)
dComUpdate is to be used when updating a record in the database(student presence for example) When this is called, call doClose() right after it to avoid database errors and close unneeded connections. Generally, at the "finally" stage of a try-catch-finally. sqlcmd The all-in-one SQL query (UPDATABLE) method.
References ams.dbControl.doConnect.
static String ams.dbControl.getID(String uid)
References ams.dbControl.dbComd, ams.dbControl.doClose.
static Connection ams.dbControl.doConnect()
Connects to the database. I've had issues with this bit. It continuously tried to connect to a deleted scheme, therefore I manually set a direct connection to the schema we're using with "con.setSchema("AMS");" username = "test" username for the DB password = "test" username for the DB con to carry out the connection to other methods
Referenced by ams.dbControl.dbComd, ams.dbControl.dbComdUpdate, ams.Presence.MarkPresent, ams.Presence.UpPresence, ams.Presence.DownPresence, ams.Presence.InstructorPresence.
static void ams.dbControl.doClose()
Closes the connection in the agreed upon safe pattern: ResultSet ¬ Statement ¬ Connection. Should generally be added to the finally block after the try-catch. Based on ( https://stackoverflow.com/questions/2225221/closing-database-connections-in-java )
Referenced by ams.CardConnection.run, ams.ClassManager.classListFiller2, ams.ClassManager.timeListFiller2, ams.ClassManager.class2ListFiller2, ams.ClassManager.timingsListFiller2, ams.ClassThread.ActiveClassesList, ams.dbControl.getID, ams.dbLookUp.uidCheck, ams.InterfaceCmds.getCurrentClass, ams.InterfaceCmds.getCurrentUID, ams.InterfaceCmds.getCurrentSwipe, ams.Presence.timeCheck, ams.Presence.FifteenMinActivate, ams.Presence.MarkPresent, ams.Presence.UpPresence, ams.Presence.DownPresence, ams.Presence.InstructorPresence, ams.student.student, ams.student.cardIDLookUp.