/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ams;

import static com.sun.javafx.scene.control.skin.Utils.getResource;
import javax.swing.ImageIcon;

/**
 *
 * @author Maan Alaulaqi (201610814@aau.ac.ae)
 */
public class UserInterface extends javax.swing.JFrame {
    protected final ImageIcon ICON_ACTIVE = createImageIcon("Start_ACTIVE.png", "Card reader currently active.");// = new ImageIcon("/images/Start_ACTIVE.png");
    protected final ImageIcon ICON_INACTIVE = createImageIcon("ams/src/images/Start_NOTACTIVE.png", "Card reader currently active.");//// = new ImageIcon("/images/Start_NOTACTIVE.png");

    
    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
    }
    
    /** Returns an ImageIcon, or null if the path was invalid. 
     * This is to allow images to brought in without a NullPointerException
     * Resourced from :
     * https://stackoverflow.com/questions/13151979/null-pointer-exception-when-an-imageicon-is-added-to-jbutton-in-netbeans
     */
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        ActiveCheck = new javax.swing.JLabel();
        main_start = new javax.swing.JPanel();
        currentClass = new java.awt.Label();
        classCall = new java.awt.Label();
        mainBG_start = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(0, 0, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(798, 584));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(798, 584));

        jPanel2.setMaximumSize(new java.awt.Dimension(798, 584));
        jPanel2.setMinimumSize(new java.awt.Dimension(798, 584));
        jPanel2.setPreferredSize(new java.awt.Dimension(798, 584));

        ActiveCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Start_NOTACTIVE.png"))); // NOI18N

        main_start.setMinimumSize(new java.awt.Dimension(798, 584));
        main_start.setLayout(null);

        currentClass.setBackground(new java.awt.Color(255, 255, 255));
        currentClass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        currentClass.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        currentClass.setText("Current class: ");
        main_start.add(currentClass);
        currentClass.setBounds(90, 170, 160, 40);

        classCall.setBackground(new java.awt.Color(255, 255, 255));
        classCall.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        classCall.setText(InterfaceCmds.getCurrentClass(1));
        main_start.add(classCall);
        classCall.setBounds(250, 167, 390, 50);
        classCall.getAccessibleContext().setAccessibleName("");

        mainBG_start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainBG_start.png"))); // NOI18N
        mainBG_start.setAlignmentY(0.0F);
        main_start.add(mainBG_start);
        mainBG_start.setBounds(0, 0, 798, 584);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(110, Short.MAX_VALUE)
                .addComponent(ActiveCheck)
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(main_start, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(ActiveCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(main_start, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLayeredPane1.add(jPanel2);
        jPanel2.setBounds(0, 0, 798, 584);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
//        ImageIcon ACTIVE = 
       /* ImageIcon ICON_ACTIVE1;
        ICON_ACTIVE1 = createImageIcon2("/images/Start_ACTIVE.png", "Card reader currently active.");
         ICON_INACTIVE = new createImageIcon("/images/Start_NOTACTIVE.png");
        */
       UserInterface need = new UserInterface(2); //
       need.updateActiveCheck(true); 
//        ActiveCheck.setIcon(ICON_ACTIVE);
    }
     public ImageIcon createImageIcon(String path, String description) {
        java.net.URL imgURL = getClass().getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL, description);
        } else {
            System.out.println("Couldn't find file: " + path);
            return null;
        }
    }
   public ImageIcon getImageIcon1(ImageIcon x){
       ImageIcon u;
        u = x;
       return u;
   }
   /**
    * Need a way to access non-static methods from static context
    * Referenced from https://www.javacodegeeks.com/2017/10/can-non-static-method-access-static-variablemethod-java.html
    * 
    * @param d 
    */
   public UserInterface(int d){} 
    private void updateActiveCheck(boolean success) {
        if(success) {            
            ActiveCheck.setIcon(ICON_ACTIVE);
        }
        else if(!success) {
            ActiveCheck.setIcon(ICON_INACTIVE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel ActiveCheck;
    private java.awt.Label classCall;
    private java.awt.Label currentClass;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mainBG_start;
    private javax.swing.JPanel main_start;
    // End of variables declaration//GEN-END:variables

    
}
