.TH "ams" 3 "Sun May 12 2019" "Version 2.3" "Attendance Management System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBams_main\fP"
.br
.ti -1c
.RI "class \fBamsActivate\fP"
.br
.ti -1c
.RI "class \fBCardConnection\fP"
.br
.ti -1c
.RI "class \fBClassManager\fP"
.br
.ti -1c
.RI "class \fBClassThread\fP"
.br
.ti -1c
.RI "class \fBdbControl\fP"
.br
.ti -1c
.RI "class \fBdbLookUp\fP"
.br
.ti -1c
.RI "class \fBFileSaver\fP"
.br
.ti -1c
.RI "class \fBInterfaceCmds\fP"
.br
.ti -1c
.RI "class \fBPresence\fP"
.br
.ti -1c
.RI "class \fBstudent\fP"
.br
.ti -1c
.RI "class \fBupdateChecker\fP"
.br
.ti -1c
.RI "class \fBUserInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Attendance Management System from the source code\&.
