.TH "ams.updateChecker" 3 "Sun May 12 2019" "Version 2.3" "Attendance Management System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ams.updateChecker
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBupdateActiveCheck\fP (boolean success)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is meant to change the UI of the "ACTIVE/NOT ACTIVE phase of the AMS\&. I made it to avoid having to deal with static/non-static arguments that tended to come up during the development phase of this project\&. 
.PP
\fBAuthor:\fP
.RS 4
Maan Alaulaqi (201610814@aau.ac.ae) 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void ams\&.updateChecker\&.updateActiveCheck (boolean success)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Attendance Management System from the source code\&.
