.TH "C:/Users/thema/OneDrive/Desktop/Attendance Management System/ams Directory Reference" 3 "Sun May 12 2019" "Version 2.3" "Attendance Management System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thema/OneDrive/Desktop/Attendance Management System/ams Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
