.TH "C:/Users/thema/OneDrive/Desktop/Attendance Management System/ams/src/ams/createImageIcon.java" 3 "Sun May 12 2019" "Version 2.3" "Attendance Management System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thema/OneDrive/Desktop/Attendance Management System/ams/src/ams/createImageIcon.java
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Attendance Management System from the source code\&.
