.TH "C:/Users/thema/OneDrive/Desktop/Attendance Management System/ams/src/ams/dbLookUp.java" 3 "Sun May 12 2019" "Version 2.3" "Attendance Management System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/thema/OneDrive/Desktop/Attendance Management System/ams/src/ams/dbLookUp.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBams\&.dbLookUp\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBams\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Attendance Management System from the source code\&.
