.TH "deprecated" 3 "Sun May 12 2019" "Version 2.3" "Attendance Management System" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 

.IP "\fBClass \fBams\&.student\fP \fP" 1c
An early class assigned for students 
.IP "\fBMember \fBams\&.student\&.SQLStudent\fP (String column, String table)\fP" 1c
 The idea here is to have a ready SQL statement that can be multi-purposed 
.PP

