CREATE TABLE AMS.ATTEND (
	ID INTEGER NOT NULL,
	STUDENT_ID INTEGER NOT NULL,
	CLASS_ID INTEGER NOT NULL,
	CLASS_ENROLLMENT_DATE DATE NOT NULL,
	ATTENDANCE_OUTCOME_ID INTEGER NOT NULL,
	PRIMARY KEY (ID)
)	
ALTER TABLE AMS.ATTEND
	ADD FOREIGN KEY (ATTENDANCE_OUTCOME_ID) 
	REFERENCES AMS.ATTENDANCE_OUTCOME (ID)	


