CREATE TABLE AMS.CLASS_SCHEDULE (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	SECTION VARCHAR(128),
	START_TIME TIME,
	END_TIME TIME,
	FIRSTT_CLASS VARCHAR(15) DEFAULT 'd' NOT NULL,
	SECOND_CLASS VARCHAR(15) DEFAULT 'd' NOT NULL
)	
