CREATE TABLE AMS.INSTRUCTOR (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	CARD_ID VARCHAR(128) DEFAULT 'DEFAULT NULL' NOT NULL,
	EMPLOYEE_ID VARCHAR(128) DEFAULT 'default null' NOT NULL,
	FIRST_NAME VARCHAR(128) DEFAULT 'DEFAULT NULL' NOT NULL,
	LAST_NAME VARCHAR(128) DEFAULT 'DEFAULT NULL' NOT NULL,
	TITLE VARCHAR(64),
	BIRTH_DATE DATE DEFAULT 'DEFAULT NULL' NOT NULL,
	CONTACT_PHONE VARCHAR(128),
	CONTACT_MOBILE VARCHAR(128),
	CONTACT_MAIL VARCHAR(128),
	PRIMARY KEY (ID)
)	
