CREATE TABLE AMS.INSTRUCTOR_CLASS (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	CLASS_ID INTEGER,
	INSTRUCTOR_ID INTEGER,
	CLASS_SECTION VARCHAR(128) DEFAULT 'd' NOT NULL
)	
ALTER TABLE AMS.INSTRUCTOR_CLASS
	ADD FOREIGN KEY (CLASS_ID) 
	REFERENCES AMS.CLASS (ID)	

ALTER TABLE AMS.INSTRUCTOR_CLASS
	ADD FOREIGN KEY (INSTRUCTOR_ID) 
	REFERENCES AMS.INSTRUCTOR (ID)	


