CREATE TABLE AMS.STUDENT (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
	CARD_ID VARCHAR(128),
	STUDENT_ID VARCHAR(128),
	FIRST_NAME VARCHAR(128) NOT NULL,
	LAST_NAME VARCHAR(128) NOT NULL,
	BIRTH_DATE DATE,
	CONTACT_MOBILE VARCHAR(128),
	CONTACT_MAIL VARCHAR(256),
	PRIMARY KEY (ID)
)	
